blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-exmaple
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2020/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2020/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2020/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

]

bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkDV, BookmarkLV

app_name='bookmark'

urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

django_practice02/urls.py
from django.contrib import admin
from django.urls import path, include

from django_practice02.views import HomeView
from django_practice02.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    #Login
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', UserCreateView.as_view(), name='register'),
#    path('accounts/register/done', UserCreateDoneTV.as_veiw(), name='register_done'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        user = self.create_user(
            email,
            password=password,
            username=username,
            #date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    username = models.CharField(max_length=25)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.is_admin

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT')
    create_dt = models.DateField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateField('MODIFY DATE', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

bookmark/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self):
        return self.title

account/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import MyUser

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ('email', 'username')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = MyUser
        fields = ('email', 'password', 'username',
                  'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]

account/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post
# Create your views here.

class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from bookmark.models import Bookmark

# Create your views here.
class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

django_practice02/views.py
from django.views.generic import TemplateView

from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class HomeView(TemplateView):
    template_name = 'home.html'

class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width", initial-scale="1">
    <title>{% block title %}Django Web programming{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    {% block extra-style %} {% endblock %}
</head>
<bodys style="padding-top:90px;">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand font-weight-bold text-info overflow-auto" href="/">Blue-collar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-dark" href="{% url 'bookmark:index' %}">Bookmark</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-dark" href="{% url 'blog:index' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-dark" href="">Photo</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
          <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
          <a class="dropdown-item" href="">Search</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="" method="post">{% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="검색" name="search_word">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <!-- LOGIN -->
    <ul class="navbar-nav ml-5 mr-5">
        <li class="nav-item dropdown mx-1 btn">
            {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-black" href="#" data-toggle="dropdown">
                <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">비밀번호변경</a>
                    <a class="dropdown-item" href="">포트폴리오 수정</a>
                </div>
            {% else %}
                <a class="nav-link dropdown-toggle text-black" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;로그인&ensp;
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'login' %}">로그인</a>
                    <a class="dropdown-item" href="{% url 'register' %}">회원가입</a>
                </div>
            {% endif %}
        </li>
    </ul>
  </div>
</nav>

{% block content %}{% endblock %}

{% block footer %} {% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
{% block extra-script %} {% endblock %}
</bodys>
</html>

templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}
{% block content %}
<h1>Blog List</h1>
<br>

{% for post in posts %}
    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
    {{ post.modify_dt|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

<br>
<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}
{% block content %}
    <h1>Post Archives until {% now "N d, Y" %}</h1>
    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a></li>
        {% endfor %}
    </ul>
    <br/>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}
{% block content %}

    <h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}
{% block content %}

    <h1>Post Archives for {{ month|date:"N, Y" }}</h1>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/blog/post_archive_year.html
  
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}
{% block content %}

    <h1>Post Archives for {{ year|date:"Y" }}</h1>

    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:'F' }}</a></li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}

<h2>{{ object.title }}</h2>
<p>
    {% if object.get_previous %}
        <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
            &laquo;-- {{ object.get_previous }}
        </a>
    {% endif %}

    {% if object.get_next %}
        | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
    {{ object.get_next }} --&raquo;
    </a>
    {% endif %}
</p>

<p>{{ object.modify_dt|date:"j F Y" }}</p>
<br>

<div>
    {{ object.content|linebreaks }}
</div>
{% endblock %}

templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block itle %}bookmark_detail.html{% endblock %}



{% block content %}
    <h1>{{ object.title }}</h1>
    <ul>
        <li>URL : <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
{% endblock %}

templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}bookmark_list.html{% endblock %}
{% block content %}


    <h1>Bookmark List</h1>
    <ul>
        {% for bookmark in object_list %}
        <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
    background-image: url("{% static 'img/blue.png' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 70%;
    height: 500px;
    border-top: 10px  white;
    border-bottom:10px  white;
    padding: 20px 0 0 20px;
}
.title{
    color: darkblue;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: black;
    font-style: italic;
}
/* margin.css */

        .mtb-0{
          margin-top: 0px;
          margin-bottom: 0px;
          margin-left: 0px;
        }
        .mb-3, .my-3 {
          margin-bottom: 16px!important;
        }

        .my-3{
          margin-top: 16px!important;
        }

        .mx-auto {
          margin-right: auto!important;
          margin-left: auto!important;
        }
        /* margin.css end*/

        /* grid.css */
        .gutter-md-spacious>[class*=col-]{
          padding-right: 24px!important;
          padding-left: 24px!important;
        }
        /* grid.css end */

         .py-sm-8{
            padding-top : 64px!important;
            padding-bottom : 64px!important;
        }

        .background{
            /*background-color: 	#008080;*/
            background-color: #ededed;
            background-position: center 10%;
            background-size:conver;
        }

        .p-responsive{
            padding-right: 16px!important;
            padding-left: 16px!important;
        }

        .position-relative {
            position: relative!important;
        }

        .container-lg, .container-xl {
            margin-left: auto;
            margin-right: auto;
        }
        .container-lg{
            max-width:1012px;
        }

        .d-md-flex {
           display: flex!important;
        }

        .flex-items-center {
           align-items: center!important;
        }

        .gutter-md-spacious {
            margin-right: -24px;
            margin-left: -24px;
        }
        /*font.css */
        .h5 {
          font-size: 14px!important;
          font-weight: 600!important;
        }
        .h1{
          font-size: 80px!important;
        }
        .h2{
          font-size: 60px!important;
        }
        .maincolor{
          color:#1d77ff
          /*color: #00c3ff*/
        }
        /*font.css end */
        label {
          cursor: default;
        }

        .bg-gray-light{
          background-color: white;
        }

        .rounded-1{
          border-radius: 5px!important;
        }

        /* button.css */
        .btn-mktg{
          display: inline-block;
          padding: 16px 24px;
          font-size: 14px;
          font-weight: 500;
          color: #fff;
          white-space: nowrap;
          vertical-align: middle;
          cursor: pointer;
          -webkit-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
          user-select: none;
          background-color: #1074e7;
          border: 1px solid #1074e7;
          border-radius: 3px;
          transition: .2s;
          -webkit-appearance: none;
          -moz-appearance: none;
          appearance: none;
        }

        .btn-primary-mktg {
          /*background-color: #2ebc4f;
          border-color: #2ebc4f;*/
          background-color: #1d77ff;
          border-color: #1d77ff;
        }

        .btn-large-mktg {
          padding: 20px 32px;
          font-size: 16px;
          font-weight: bold;
        }
        /* button.css end */
        /* form-group.css */

        .form-group.required .form-group-header label::after, .form-group.required dt label::after {
            padding-left: 5px;
            color: #cb2431;
            content: "*";
        }
        /* form-group.css end */
</style>
{% endblock %}
{% block content %}
<header class="py-5 mb-5 background">
  <div class="container h-100 py-sm-8">
    <div class="row h-100 align-items-center">
      <div class="col-md-7 text-md-left">
        <h1 class ="h1 maincolor font-weight-bold mtb-0">Blue collar</h1>
        <h1 class ="h2 maincolor font-weight-bold mtb-0">Portfolio</h3>
         <p>[1]테스트 문구 테스트 문구 테스트 문구 테스트 문구 테스트 문구<br/>
             [2]테스트 문구 테스트 문구 테스트 문구 테스트 문구
         </p>
      </div>
      <div class="mx-auto col-sm-8 col-md-5 hide-sm py-3 ">
        <div class="rounded-1 bg-gray-light text-gray py-4 px-4 px-md-3 px-lg-4">
          <form class="text-gray-dark" autocomplete="off" method="post">
            <!--username-->
            <dl class="form-group mt-0 required">
              <dt class="input-label">
                <label class="form-label h5" for="user">Username</label>
              </dt>
              <dd>
                <input type="text" name="user[login]" id="user[login]" class="form-control form-control-lg input-block" autocomplete="off" spellcheck="false">
              </dd>
            </dl>
            <dl class="form-group mt-0 required">
              <dt class="input-label">
                <label class="form-label h5" for="Email">Email</label>
              </dt>
              <dd>
                <input type="text" name="Email" id="Email" class="form-control form-control-lg input-block" autocomplete="off" spellcheck="false">
              </dd>
            </dl>
            <dl class="form-group mt-0 required">
              <dt class="input-label">
                <label class="form-label h5" for="Password">Password</label>
              </dt>
              <dd>
                <input type="password" name="Password" id="Password" class="form-control form-control-lg input-block" autocomplete="off" spellcheck="false">
              </dd>
            </dl>
            <br/>
            <br/>
            <button type="submit" class="btn-mktg btn-primary-mktg btn-large-mktg f4 btn-block my-3">Blue Collar 회원가입</button>
            <br/>
          </form>
        </div>
      </div>
    </div>
  </div>
</header>

{% endblock %}